version: '3'

volumes:
  media:
  pg_data:
  static:

services:
  db:
    env_file: .env
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    depends_on:
      - db
    env_file: .env
    image: alekssa/foodgram_backend
    volumes:
      - static:/backend_static
      - media:/app/media/
  frontend:
    command: cp -r /app/build/. /frontend_static/
    env_file: .env
    image: alekssa/foodgram_frontend
    volumes:
      - static:/frontend_static
  gateway:
    depends_on:
      - backend
      - frontend
    env_file: .env
    image: alekssa/foodgram_infra
    ports:
      - 8000:80
    volumes:
      - static:/staticfiles/
      - media:/app/media/
      - ./docs/:/usr/share/nginx/html/api/docs/